[package]
name = "nvram-sim"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
common = { path = "../common" }
anyhow = { workspace = true }
serde_json = { workspace = true }
